#example-open-playbook.yml
# sets up a squid proxy that accepts all requests from RFC private networks
- name: Squid (open private)
  hosts: http-proxy-open
  become: true
  vars: 
    - squid_acl_localnet:
      - 10.0.0.0/8
      - 172.16.0.0/16
      - 192.168.0.0/16
  roles:
    - http-proxy